---
-   name: "install n"
    become: yes
    npm:
        name: n
        global: yes
        production: yes

-   name: "install nodejs 13.8.0"
    become: yes
    shell: n 13.8.0

-   name: "Install PM2"
        npm:
            name: pm2
            global: yes
            production: yes
            state: present
