---
 - name: "Create backend directory"
   file:
     path: /home/ubuntu/backend-app
     state: directory

 - name: "Extract backend files"
   unarchive:
     src: artifact.tar.gz
     dest: /home/ubuntu/backend-app

 - name: "Installing Node Dependencies"
   become: true
   apt:
      name: npm
      state: latest
      update_cache: true

 - name: "Execute Node app with pm2"
   shell: |
       cd  /home/ubuntu/backend-app/dist
       pm2 stop default
       pm2 start -f main.js

   register: execute_node

 - name: "Print message"
   debug:
      msg: "{{ execute_node.stdout_lines }}"

 - name: "Configure pm2 to start as service"
   become: true
   shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
